name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: test

    steps:
      - name: Install basic dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y vagrant virtualbox
